# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
dist: trusty
latex: false
fortran: false
r_build_args: '--no-manual'

jobs:
  include:
  - r: devel
  - r: 3.1
  - r: 3.4
    warnings_are_errors: false

  - stage: full
    os: osx
    brew_packages: libssh
      before_install: brew upgrade libssh # temp fix for outdated travis
  - r: release
 
addons:
  apt:
    packages:
    - libssh-dev

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
