# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
dist: trusty
latex: false
fortran: false
r_build_args: '--no-manual'

matrix:
  include:
    - r: devel
    os: linux
    - r: devel
    - r: 3.1
    - r: 3.4
    - r: release
    os: osx

addons:
  apt:
    packages:
    - libssh-dev

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
