# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
dist: trusty
latex: false
fortran: false
r_build_args: '--no-manual'

before_install:
  - sudo apt-get install -y libssh-dev

jobs:
  include:
  - r: devel
  - r: 3.1
    warnings_are_errors: false

  - stage: full
    os: osx
  - r: release
    
r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
